apiVersion: v1
kind: ConfigMap
metadata:
  name: bloodhounds-web
data:
  NODE_ENV: production
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_WEB_URL: https://bloodhounds.homes
  NEXT_PUBLIC_PROJECT_NAME: bloodhounds
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-ZYCY37SYLV
  NEXT_PUBLIC_CLARITY_PROJECT_ID: wb4ttwal07
  NEXT_PUBLIC_DEFAULT_THEME: dark
  NEXT_PUBLIC_AUTH_DISABLED: "true"
