apiVersion: v1
kind: ConfigMap
metadata:
  name: paradox-trello-web
data:
  NODE_ENV: production
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_WEB_URL: https://paradox-trello.lol
  NEXT_PUBLIC_PROJECT_NAME: paradox-trello
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-2T32WKRTVM
  NEXT_PUBLIC_CLARITY_PROJECT_ID: wbhm990q09
  NEXT_PUBLIC_DEFAULT_THEME: dark
  NEXT_PUBLIC_AUTH_DISABLED: "true"
