apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    email: gateszhang92@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dns-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token
