apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paradox-trello
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - dns-issuer.yaml
  - ingress.yaml
  - preview-ingress.yaml
