apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paradox-trello-preview
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paradox-trello.144.91.77.245.sslip.io
      secretName: paradox-trello-preview-tls
  rules:
    - host: paradox-trello.144.91.77.245.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paradox-trello-web
                port:
                  name: http
