apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paradox-trello
resources:
  - ../../base
images:
  - name: ghcr.io/example/paradox-trello
    newName: registry.144.91.77.245.sslip.io/paradox-trello
    newTag: "56e949209a0cf16e572042f3fc97009c92953d49"
